// Generated by Enterprise IDE Plugin from IDE factory L.L.C.
package services.command.backend
{

	import com.adobe.cairngorm.commands.ICommand;
	import com.adobe.cairngorm.control.CairngormEvent;
	import com.adobe.cairngorm.control.CairngormEventDispatcher;
	
	import services.business.backend.AddCityDelegate;
	import services.events.MsgEvent;
	import services.events.backend.AddCityEvent;
	import framework.model.AppModelLocator;
	import services.vo.common.CityVO;
	
	import h2olib.control.enum.MessageKind;
	import h2olib.control.enum.MessageShowType;
	
	import mx.rpc.IResponder;

	public class AddCityCommand implements ICommand, IResponder 
	{
		private var model:AppModelLocator = AppModelLocator.getInstance();
		
		private var addCityComplete:Function;
		private var addCityError:Function;
		private var addCityEvent:AddCityEvent;
		
		public function execute(event:CairngormEvent):void
		{
			addCityEvent = event as AddCityEvent; 
			addCityComplete = addCityEvent.addCityComplete;
			addCityError = addCityEvent.addCityError;
			var delegate:AddCityDelegate = new AddCityDelegate(this);
			delegate.addCity(addCityEvent);
		}

		public function result(data:Object):void
		{
			addCityComplete(data as CityVO);
			model.appEnabled--;
		}

		public function fault(info:Object):void
		{
			addCityError();
			new MsgEvent(MessageKind.ERROR,
						"Error",
						model.lastResponse.aMessageStack.toString(),
						MessageShowType.MSG_BAR).dispatch();
			model.appEnabled--;
		}

	}

}