// Generated by Enterprise IDE Plugin from IDE factory L.L.C.
package services.vo.hotels
{

	import com.adobe.cairngorm.vo.IValueObject;
	/**
	* The HotelRoomStatusVO class is 
	*
	* @author  Anton Kirzyk / Ramada
	*
	* @version $Revision 1.0 $ $Date: 2009-07-18 11:52:03 +0300 (Сб, 18 июл 2009) $
	*
	*/
	 
	[RemoteClass(alias="MapHotelRoomStatus")]
	[Bindable]
	public class HotelRoomStatusVO implements IValueObject 
	{
		public var lId:Number;
		public var sName:String;
		public var sCode:String;
	}

}