// Generated by Enterprise IDE Plugin from IDE factory L.L.C.
package services.events.backend
{

	import com.adobe.cairngorm.control.CairngormEvent;
	
	import services.vo.common.CityVO;

	public class AddCityEvent extends CairngormEvent 
	{

		public var city:CityVO;
		
		public var addCityComplete:Function;
		public var addCityError:Function;
		
		public function AddCityEvent(type:String, bubbles:Boolean=false, cancelable:Boolean=false)
		{
			super(type, bubbles, cancelable);
		}

	}

}