package model.modules
{
	import flashx.textLayout.formats.Category;
	
	import mx.collections.ArrayCollection;
	
	import vo.CategoryVO;
	import vo.ProductVO;

	[Bindable]
	public class ModCollections
	{
		public function ModCollections()
		{
		}
		
		public var categories:ArrayCollection = new ArrayCollection(
			[
				new CategoryVO(1, "Молочные продукты"),
				new CategoryVO(2, "Хлеб, мука"),
				new CategoryVO(3, "Крупа в сухом виде"),
				new CategoryVO(4, "Мясо, птица"),
				new CategoryVO(5, "Рыба, морепродукты"),
				new CategoryVO(6, "Овощи, бахчевые, бобовые"),
				new CategoryVO(7, "Фрукты"),
				new CategoryVO(8, "Сухофрукты"),
				new CategoryVO(9, "Ягоды"),
				new CategoryVO(10, "Грибы"),
				new CategoryVO(11, "Орехи"),
				new CategoryVO(12, "Пряности, приправы"),
				new CategoryVO(13, "Масло растительное"),
				new CategoryVO(14, "Консервы"),
				new CategoryVO(15, "Сладости"),
				new CategoryVO(16, "Варенье"),
				new CategoryVO(17, "Мороженое"),
				new CategoryVO(18, "Напитки, соки"),
				new CategoryVO(19, "Алкоголь")
				
				
				
			]		
		);
		
		public var products:ArrayCollection = new ArrayCollection(
			[
				//	Молочные продукты
				new ProductVO(1, 1	,"Брынза", 	0.5	),
				new ProductVO(1, 2	,"Йогурт несладкий 1,5% - 6% жирности", 	3.5	),
				new ProductVO(1, 3	,"Йогурт сладкий", 	8.5	),
				new ProductVO(1, 4	,"Йогурт плодово-ягодный", 	14	),
				new ProductVO(1, 5	,"Йогурты с фруктовыми добавками", 	16	),
				new ProductVO(1, 6	,"Какао со сгущенным молоком и сахаром (консерв.)", 	52	),
				new ProductVO(1, 7	,"Кофе со сгущенным молоком и сахаром (консерв.)", 	53	),
				new ProductVO(1, 8	,"Кефир нежирный до 2,5% жирности", 	4	),
				new ProductVO(1, 9	,"Кумыс из коровьего молока", 	6.3	),
				new ProductVO(1, 10	,"Кумыс из кобыльего молока", 	5	),
				new ProductVO(1, 11	,"Майонез столовый", 	3.3	),
				new ProductVO(1, 12	,"Маргарин", 	1	),
				new ProductVO(1, 13	,"Масло сладко-сливочное несоленое «33 коровы»", 	0.8	),
				new ProductVO(1, 14	,"Масло сладко-сливочное «Вологодское»", 	0.8	),
				new ProductVO(1, 15	,"Масло сладко-сливочное несоленое «Любительское»", 	1	),
				new ProductVO(1, 16	,"Масло сладко-сливочное несоленое «Крестьянское»", 	1.3	),
				new ProductVO(1, 17	,"Масло топленное", 	0	),
				new ProductVO(1, 18	,"Молоко пастеризованное нежирное", 	4.9	),
				new ProductVO(1, 19	,"Молоко стерилизованное 1,5%-2,5% жирности", 	4.8	),
				new ProductVO(1, 20	,"Молоко стерилизованное 3,2% жирности", 	4.7	),
				new ProductVO(1, 21	,"Молоко топленное нежирное", 	5	),
				new ProductVO(1, 22	,"Молоко топленное 1% жирности", 	4.8	),
				new ProductVO(1, 23	,"Молоко топленное 4% жирности", 	4.7	),
				new ProductVO(1, 24	,"Молоко сухое «Смоленское» 15% жирности", 	45	),
				new ProductVO(1, 25	,"Молоко сухое 25% жирности", 	39	),
				new ProductVO(1, 26	,"Молоко сгущенное с сахаром (консерв.)", 	55	),
				new ProductVO(1, 27	,"Молоко сгущенное стерилизованное (консерв.)", 	10	),
				new ProductVO(1, 28	,"Простокваша нежирная", 	3.8	),
				new ProductVO(1, 29	,"Простокваша 1%-2,5% жирности", 	4.1	),
				new ProductVO(1, 30	,"Ряженка", 	4.2	),
				new ProductVO(1, 31	,"Сливки 8%-10% жирности", 	4.5	),
				new ProductVO(1, 32	,"Сливки 20% жирности", 	4	),
				new ProductVO(1, 33	,"Сливки 25% жирности", 	3.9	),
				new ProductVO(1, 34	,"Сливки 35% жирности", 	3.2	),
				new ProductVO(1, 35	,"Сыр домашний нежирный", 	1.5	),
				new ProductVO(1, 36	,"Сыр домашний 4% жирности", 	1.5	),
				new ProductVO(1, 37	,"Сыр Адыгейский", 	1.5	),
				new ProductVO(1, 38	,"Сыр Бийский", 	0	),
				new ProductVO(1, 39	,"Сыр Голландский", 	0	),
				new ProductVO(1, 40	,"Сыр Колбасный (копченный)", 	4	),
				new ProductVO(1, 41	,"Сыр Костромской", 	0	),
				new ProductVO(1, 42	,"Сыр Костромской (плавленный)", 	2.5	),
				new ProductVO(1, 43	,"Сыр Латвийский", 	0	),
				new ProductVO(1, 44	,"Сыр Пошехонский", 	0	),
				new ProductVO(1, 45	,"Сыр Прибалтийский", 	0	),
				new ProductVO(1, 46	,"Сыр Рокфор", 	0	),
				new ProductVO(1, 47	,"Сыр Российский", 	0	),
				new ProductVO(1, 48	,"Сыр Российский (плавленный)", 	2.5	),
				new ProductVO(1, 49	,"Сыр Сулугуни", 	0.5	),
				new ProductVO(1, 50	,"Сыр Угличский", 	0	),
				new ProductVO(1, 51	,"Сыр Швейцарский", 	0	),
				new ProductVO(1, 52	,"Сыр Чеддер", 	0	),
				new ProductVO(1, 53	,"Сыр Ярославский", 	0	),
				new ProductVO(1, 54	,"Сырки творожные сладкие 8% жирности", 	12	),
				new ProductVO(1, 55	,"Сырки творожные сладкие с ванилином 16% жирности", 	9.5	),
				new ProductVO(1, 56	,"Сырки творожные детские 23% жирности", 	19	),
				new ProductVO(1, 57	,"Сырки глазированные с ванилином", 	33	),
				new ProductVO(1, 58	,"Тан (айран)", 	3	),
				new ProductVO(1, 59	,"Творог нежирный", 	3.3	),
				new ProductVO(1, 60	,"Творог мягкий диетический нежирный", 	3.3	),
				new ProductVO(1, 61	,"Творог 2%-5% жирности", 	3	),
				new ProductVO(1, 62	,"Творог 18% жирности", 	2.8	),
				new ProductVO(1, 63	,"Творог мягкий диетический 4% жирности", 	3	),
				new ProductVO(1, 64	,"Творожная масса сладкая с ванилином 16% жирности", 	9.5	),
				new ProductVO(1, 65	,"Творожная масса сладкая 8% жирности", 	12	),
				new ProductVO(1, 66	,"Творожная масса сладкая с ванилином 20% жирности", 	15	),
				new ProductVO(1, 67	,"Творожная масса сладкая с изюмом 23% жирности", 	27	),
				new ProductVO(1, 68	,"Творожная масса сладкая с курагой", 	29	),
				
				//	Хлеб, мука
				new ProductVO(2,	1,"Батон нарезной из пшеничной муки высшего сорта", 	51),
				new ProductVO(2, 2,"Бородинский", 	40),
				new ProductVO(2, 3,"Диабетический", 	38),
				new ProductVO(2, 4,"Зерновой", 	43),
				new ProductVO(2, 5,"Лаваш армянский", 	56),
				new ProductVO(2, 6,"Паляница", 	50),
				new ProductVO(2, 7,"Пшеничный хлеб", 	50),
				new ProductVO(2, 8,"Ржаной", 	34),
				new ProductVO(2, 9,"Рижский", 	51),
				new ProductVO(2, 10,"Украинский", 	40),
				new ProductVO(2, 11,"Булочки молочные", 	50),
				new ProductVO(2, 12,"Булочки сдобные", 	51),
				new ProductVO(2, 13,"Баранки сдобные", 	60),
				new ProductVO(2, 14,"Бублики", 	58),
				new ProductVO(2, 15,"Крахмал картофельный", 	79),
				new ProductVO(2, 16,"Крахмал кукурузный", 	85),
				new ProductVO(2, 17,"Лапша яичная", 	68),
				new ProductVO(2, 18,"Лепешки ржаные", 	44),
				new ProductVO(2, 19,"Макароны", 	69),
				new ProductVO(2, 20,"Мука пшеничная высший сорт", 	71),
				new ProductVO(2, 21,"Мука пшеничная первый сорт", 	69),
				new ProductVO(2, 22,"Мука пшеничная второй сорт", 	65),
				new ProductVO(2, 23,"Мука обойная", 	62),
				new ProductVO(2, 24,"Мука из зародышей пшеницы", 	33),
				new ProductVO(2, 25,"Мука ржаная сеяная", 	64),
				new ProductVO(2, 26,"Мука гречневая", 	71),
				new ProductVO(2, 27,"Мука кукурузная", 	70),
				new ProductVO(2, 28,"Мука рисовая", 	80),
				new ProductVO(2, 29,"Мука соевая не обезжиренная", 	18),
				new ProductVO(2, 30,"Мука соевая обезжиренная", 	22),
				new ProductVO(2, 31,"Печенье затяжное", 	70),
				new ProductVO(2, 32,"Печенье миндальное", 	67),
				new ProductVO(2, 33,"Печенье сахарное", 	74),
				new ProductVO(2, 34,"Печенье сдобное", 	69),
				new ProductVO(2, 35,"Пряники заварные", 	75),
				new ProductVO(2, 36,"Рожки к чаю", 	57),
				new ProductVO(2, 37,"Сушки", 	68),
				new ProductVO(2, 38,"Сушки ванильные", 	71),
				new ProductVO(2, 39,"Соломка сладкая", 	69),
				new ProductVO(2, 40,"Сухари сливочные", 	66),
				new ProductVO(2, 41,"Сухарики «Кириешки»", 	62),
				new ProductVO(2, 42,"Сухарики «Три корочки»", 	64),
				new ProductVO(2, 43,"Толокно", 	65),
				new ProductVO(2, 44,"Хлебцы докторские", 	46),
				new ProductVO(2, 45,"Хлебцы хрустящие", 	60),
				
				//	Крупа в сухом виде
				new ProductVO(3, 1,"Геркулес", 	50),
				new ProductVO(3, 2,"Гречневая", 	62),
				new ProductVO(3, 3,"Гречневая (продел)", 	66),
				new ProductVO(3, 4,"Горох лущенный", 	50),
				new ProductVO(3, 5,"Кукурузная", 	71),
				new ProductVO(3, 6,"Манная", 	67),
				new ProductVO(3, 7,"Маш", 	35),
				new ProductVO(3, 8,"Нут", 	61),
				new ProductVO(3, 9,"Овес (зерно)", 	55),
				new ProductVO(3, 10,"Овсяная", 	49),
				new ProductVO(3, 11,"Перловая", 	66),
				new ProductVO(3, 12,"Пшеница (зерно)", 	57),
				new ProductVO(3, 13,"Пшено", 	66),
				new ProductVO(3, 14,"Рожь (зерно)", 	55),
				new ProductVO(3, 15,"Рис Басмати", 	77),
				new ProductVO(3, 16,"Рис дикий", 	70),
				new ProductVO(3, 17,"Рис длиннозерный", 	78.5),
				new ProductVO(3, 18,"Рис Мистраль коричневый", 	72),
				new ProductVO(3, 19,"Рис Онтарио дикий черный", 	68),
				new ProductVO(3, 20,"Рис пропаренный", 	78),
				new ProductVO(3, 21,"Рис Техас", 	82),
				new ProductVO(3, 22,"Фасоль", 	46),
				new ProductVO(3, 23,"Чечевица", 	46),
				new ProductVO(3, 24,"Ячмень (зерно)", 	56),
				new ProductVO(3, 25,"Ячневая", 	65),
				
				//	Мясо, птица
				new ProductVO(4, 1,"Баранина, говядина", 	0),
				new ProductVO(4, 2,"Телятина, свинина", 	0),
				new ProductVO(4, 3,"Гуси, утки", 	0),
				new ProductVO(4, 4,"Кролик", 	0),
				new ProductVO(4, 5,"Курица", 	0),
				new ProductVO(4, 6,"Колбасы (варенные, полукопченые, сырокопченные, сервелат)", 0.5),
				new ProductVO(4, 7,"Колбаса «Докторская»", 	1.5),
				new ProductVO(4, 8,"Корейка", 	0),
				new ProductVO(4, 9,"Мозги", 	1),
				new ProductVO(4, 10,"Ножки свиные", 	0),
				new ProductVO(4, 11,"Окорок", 	0),
				new ProductVO(4, 12,"Печень говяжья", 	0),
				new ProductVO(4, 13,"Печень куриная", 	1.5),
				new ProductVO(4, 14,"Сало", 	0),
				new ProductVO(4, 15,"Сардельки говяжьи", 	1.5),
				new ProductVO(4, 16,"Сардельки свиные", 	2),
				new ProductVO(4, 17,"Сердце", 	0),
				new ProductVO(4, 18,"Сосиски молочные", 	1.5),
				new ProductVO(4, 19,"Язык свиной, говяжий", 	0),
				new ProductVO(4, 20,"Яйца в любом виде (штука)", 	0.5),
				new ProductVO(4, 21,"Жир свиной, говяжий", 	0),
				
				//	Рыба, морепродукты
				new ProductVO(5, 1,"Анчоусы", 	0),
				new ProductVO(5, 2,"Икра черная", 	0),
				new ProductVO(5, 3,"Икра красная", 	0),
				new ProductVO(5, 4,"Кальмары", 	4),
				new ProductVO(5, 5,"Крабы", 	2),
				new ProductVO(5, 6,"Крабовые палочки", 	15),
				new ProductVO(5, 7,"Крабовое мясо", 	12),
				new ProductVO(5, 8,"Креветки", 	0),
				new ProductVO(5, 9,"Лангуст", 	1),
				new ProductVO(5, 10,"Мидии", 	5),
				new ProductVO(5, 11,"Морской гребешок", 	1),
				new ProductVO(5, 12,"Омары", 	1),
				new ProductVO(5, 13,"Раки речные", 	1),
				new ProductVO(5, 14,"Рыба свежая, соленая, отварная", 	0),
				new ProductVO(5, 15,"Рыба копченная", 	0),
				new ProductVO(5, 16,"Рыба вяленая", 	0),
				new ProductVO(5, 17,"Устрицы", 	7),
				new ProductVO(5, 18,"Морская капуста", 	1),
				
				//	Овощи, бахчевые, бобовые
				new ProductVO(6, 1,"Арбуз", 	9),
				new ProductVO(6, 2,"Баклажаны", 	5),
				new ProductVO(6, 3,"Бобы", 	8),
				new ProductVO(6, 4,"Брюква", 	7),
				new ProductVO(6, 5,"Горошек зеленый", 	8),
				new ProductVO(6, 6,"Китайский редис", 	1),
				new ProductVO(6, 7,"Дыня", 	9),
				new ProductVO(6, 8,"Кабачок", 	4),
				new ProductVO(6, 9,"Капуста белокачанная", 	5),
				new ProductVO(6, 10,"Капуста брюссельская", 	4),
				new ProductVO(6, 11,"Капуста кольраби", 	8),
				new ProductVO(6, 12,"Капуста краснокачанная", 	5),
				new ProductVO(6, 13,"Капуста цветная", 	5),
				new ProductVO(6, 14,"Картофель", 	16),
				new ProductVO(6, 15,"Лук зеленый", 	3.5),
				new ProductVO(6, 16,"Лук-порей", 	6.5),
				new ProductVO(6, 17,"Лук репчатый", 	9),
				new ProductVO(6, 18,"Морковь", 	7),
				new ProductVO(6, 19,"Огурец парниковый", 	2),
				new ProductVO(6, 20,"Огурец свежий", 	3),
				new ProductVO(6, 21,"Огурец соленый", 	2),
				new ProductVO(6, 22,"Пастернак (корень)", 	9),
				new ProductVO(6, 23,"Помидоры", 	4),
				new ProductVO(6, 24,"Перец зеленый сладкий", 	5),
				new ProductVO(6, 25,"Перец красный сладкий", 	5),
				new ProductVO(6, 26,"Петрушка (зелень)", 	8),
				new ProductVO(6, 27,"Петрушка (корень)", 	10.5),
				new ProductVO(6, 28,"Ревень", 	2.5),
				new ProductVO(6, 29,"Редис", 	4),
				new ProductVO(6, 30,"Редька", 	6.5),
				new ProductVO(6, 31,"Репа", 	5),
				new ProductVO(6, 32,"Салат листовой", 	2),
				new ProductVO(6, 33,"Свекла", 	9),
				new ProductVO(6, 34,"Сельдерей (корень)", 	6),
				new ProductVO(6, 35,"Сельдерей (зелень)", 	2),
				new ProductVO(6, 36,"Спаржа", 	3),
				new ProductVO(6, 37,"Топинамбур", 	13),
				new ProductVO(6, 38,"Тыква", 	4),
				new ProductVO(6, 39,"Укроп (зелень)", 	4),
				new ProductVO(6, 40,"Фасоль стручковая", 	3),
				new ProductVO(6, 41,"Хрен", 	7.5),
				new ProductVO(6, 42,"Черемша", 	6),
				new ProductVO(6, 43,"Чеснок", 	5),
				new ProductVO(6, 44,"Шпинат", 	2),
				new ProductVO(6, 45,"Щавель", 	3),
				
				//	Фрукты
				new ProductVO(7, 1,"Абрикос", 	9),
				new ProductVO(7, 2,"Авокадо", 	3),
				new ProductVO(7, 3,"Айва", 	8),
				new ProductVO(7, 4,"Актинидия", 	10),
				new ProductVO(7, 5,"Алыча", 	6.5),
				new ProductVO(7, 6,"Ананас", 	11.5),
				new ProductVO(7, 7,"Апельсин", 	8),
				new ProductVO(7, 8,"Банан", 	21),
				new ProductVO(7, 9,"Вишня", 	10),
				new ProductVO(7, 10,"Гранат", 	11),
				new ProductVO(7, 11,"Грейпфрут", 	6.5),
				new ProductVO(7, 12,"Груша", 	9.5),
				new ProductVO(7, 13,"Инжир", 	11),
				new ProductVO(7, 14,"Киви", 	10),
				new ProductVO(7, 15,"Лимон", 	3),
				new ProductVO(7, 16,"Мандарин", 	8),
				new ProductVO(7, 17,"Нектарин", 	13),
				new ProductVO(7, 18,"Персик", 	9.5),
				new ProductVO(7, 19,"Рябина", 	8.5),
				new ProductVO(7, 20,"Рябина черноплодная", 	11),
				new ProductVO(7, 21,"Слива", 	9.5),
				new ProductVO(7, 22,"Терн", 	9.5),
				new ProductVO(7, 23,"Финики", 	68),
				new ProductVO(7, 24,"Хурма", 	13),
				new ProductVO(7, 25,"Черешня", 	10),
				new ProductVO(7, 26,"Шелковица", 	12.5),
				new ProductVO(7, 27,"Яблоки", 	9.5),
				
				//	Сухофрукты
				new ProductVO(8, 1,"Груша сушенная", 	49),
				new ProductVO(8, 2,"Изюм", 	66),
				new ProductVO(8, 3,"Кишмиш", 	66),
				new ProductVO(8, 4,"Курага", 	55),
				new ProductVO(8, 5,"Персик сушенный", 	58),
				new ProductVO(8, 6,"Чернослив", 	58),
				new ProductVO(8, 7,"Урюк", 	53),
				new ProductVO(8, 8,"Яблоки сушенные", 	45),
				
				//	Ягоды
				new ProductVO(9, 1,"Брусника", 	8),
				new ProductVO(9, 2,"Виноград", 	15),
				new ProductVO(9, 3,"Голубика", 	7),
				new ProductVO(9, 4,"Ежевика", 	4.5),
				new ProductVO(9, 5,"Клубника", 	6.5),
				new ProductVO(9, 6,"Клюква", 	4),
				new ProductVO(9, 7,"Крыжовник", 	9),
				new ProductVO(9, 8,"Малина", 	8),
				new ProductVO(9, 9,"Морошка", 	7),
				new ProductVO(9, 10,"Облепиха", 	5.5),
				new ProductVO(9, 11,"Смородина белая", 	8),
				new ProductVO(9, 12,"Смородина красная", 	7.5),
				new ProductVO(9, 13,"Смородина черная", 	7.5),
				new ProductVO(9, 14,"Черника", 	8),
				new ProductVO(9, 15,"Шиповник свежий", 	10),
				new ProductVO(9, 16,"Шиповник сушенный", 	21.5),
				
				//	Грибы
				new ProductVO(10, 1,"Белые", 	1),
				new ProductVO(10, 2,"Белые сушенные", 	7.5),
				new ProductVO(10, 3,"Грузди свежие", 	1),
				new ProductVO(10, 4,"Лисички свежие", 	1.5),
				new ProductVO(10, 5,"Маслята свежие", 	0.5),
				new ProductVO(10, 6,"Опята свежие", 	0.5),
				new ProductVO(10, 7,"Подберезовики", 	1.5),
				new ProductVO(10, 8,"Подберезовики сушеные", 	14),
				new ProductVO(10, 9,"Подосиновики свежие", 	1),
				new ProductVO(10, 10,"Подосиновики сушеные", 	13),
				new ProductVO(10, 11,"Рыжики", 	0.5),
				new ProductVO(10, 12,"Сморчки", 	0.2),
				new ProductVO(10, 13,"Сыроежки", 	1.5),
				new ProductVO(10, 14,"Шампиньоны", 	0.1),
				
				//	Орехи
				new ProductVO(11, 1,"Арахис", 	15),
				new ProductVO(11, 2,"Грецкие", 	12),
				new ProductVO(11, 3,"Кедровые", 	10),
				new ProductVO(11, 4,"Кешью", 	25),
				new ProductVO(11, 5,"Кокос", 	20),
				new ProductVO(11, 6,"Лещина", 	9),
				new ProductVO(11, 7,"Миндаль", 	11),
				new ProductVO(11, 8,"Фисташки", 	15),
				new ProductVO(11, 9,"Фундук", 	15),
				new ProductVO(11, 10,"Мак (семена)", 	14),
				new ProductVO(11, 11,"Подсолнечные семечки", 	18),
				new ProductVO(11, 12,"Семена кунжута", 	20),
				new ProductVO(11, 13,"Тыквенные семечки", 	12),
				
				//	Пряности, приправы
				new ProductVO(12, 1,"Горчица столовая", 	13),
				new ProductVO(12, 2,"Горчичный порошок", 	33),
				new ProductVO(12, 3,"Дрожжи прессованные", 	8.5),
				new ProductVO(12, 4,"Желатин", 	0.7),
				new ProductVO(12, 5,"Маринад овощной", 	11),
				new ProductVO(12, 6,"Соус белый", 	4),
				new ProductVO(12, 7,"Соус горчичный", 	15),
				new ProductVO(12, 8,"Соус грибной", 	5),
				new ProductVO(12, 9,"Соус клюквенный", 	13),
				new ProductVO(12, 10,"Соус красный", 	6),
				new ProductVO(12, 11,"Соус луковый", 	6),
				new ProductVO(12, 12,"Соус молочный", 	7),
				new ProductVO(12, 13,"Соус песто", 	6),
				new ProductVO(12, 14,"Соус сметанный", 	6),
				new ProductVO(12, 15,"Соус соевый", 	7),
				new ProductVO(12, 16,"Соус томатный", 	8),
				new ProductVO(12, 17,"Соус с хреном", 	4),
				new ProductVO(12, 18,"Соус черносмородиновый", 	68),
				new ProductVO(12, 19,"Соль", 	0),
				new ProductVO(12, 20,"Уксус столовый", 	0),
				new ProductVO(12, 21,"Уксус яблочный", 	5),
				
				//	Масло растительное
				new ProductVO(13, 1,"Кукурузное", 	0),
				new ProductVO(13, 2,"Подсолнечное", 	0),
				new ProductVO(13, 3,"Оливковое", 	0),
				new ProductVO(13, 4,"Рапсовое", 	0),
				new ProductVO(13, 5,"Соевое", 	0),
				
				//	Консервы
				new ProductVO(14, 1,"Зеленый горошек", 	6.5),
				new ProductVO(14, 2,"Кукуруза десертная", 	20),
				new ProductVO(14, 3,"Кукуруза сладкая", 	22),
				new ProductVO(14, 4,"Оливки", 	5),
				new ProductVO(14, 5,"Огурцы", 	3),
				new ProductVO(14, 6,"Икра кабачковая", 	8.5),
				new ProductVO(14, 7,"Икра баклажанная", 	5),
				new ProductVO(14, 8,"Икра из свеклы", 	2),
				new ProductVO(14, 9,"Салат с морской капустой", 	4),
				new ProductVO(14, 10,"Рыба натуральная в масле", 	0),
				new ProductVO(14, 11,"Рыба в томатном соусе", 	6),
				new ProductVO(14, 12,"Перец, фаршированный овощами", 	11),
				new ProductVO(14, 13,"Печень трески", 	1.2),
				new ProductVO(14, 14,"Томаты", 	4),
				new ProductVO(14, 15,"Томат-паста", 	19),
				new ProductVO(14, 16,"Томат-пюре", 	12),
				new ProductVO(14, 17,"Фасоль стручковая", 	2.5),
				new ProductVO(14, 18,"Фасоль красная", 	13),
				new ProductVO(14, 19,"Шпроты в масле", 	0),
				
				//	Сладости
				new ProductVO(15, 1,"Сахар-песок", 	99),
				new ProductVO(15, 2,"Сахар-рафинад", 	99),
				new ProductVO(15, 3,"Баунти", 	55),
				new ProductVO(15, 4,"Вафли обычные", 	65),
				new ProductVO(15, 5,"Вафли фруктовые", 	80),
				new ProductVO(15, 6,"Гематоген", 	75),
				new ProductVO(15, 7,"Грильяж в шоколаде", 	65),
				new ProductVO(15, 8,"Драже сахарное", 	98),
				new ProductVO(15, 9,"Жевательная резинка «Стиморол»", 	63),
				new ProductVO(15, 10,"Жевательная резинка «Дирол»", 	60),
				new ProductVO(15, 11,"Зефир", 	80),
				new ProductVO(15, 12,"Зефир в шоколаде", 	68),
				new ProductVO(15, 13,"Ирис", 	82),
				new ProductVO(15, 14,"Карамель глазированная", 	93),
				new ProductVO(15, 15,"Карамель леденцовая", 	96),
				new ProductVO(15, 16,"Карамель с молочной начинкой", 	91),
				new ProductVO(15, 17,"Карамель с фруктово-ягодной начинкой", 	92),
				new ProductVO(15, 18,"Карамель с шоколадно-ореховой начинкой", 	87),
				new ProductVO(15, 19,"Конфеты-помадка", 	83),
				new ProductVO(15, 20,"Конфеты шоколадные", 	51),
				new ProductVO(15, 21,"Мармелад", 	76),
				new ProductVO(15, 22,"Мармелад фруктово-ягодный в шоколаде", 	64),
				new ProductVO(15, 23,"Мед", 	75),
				new ProductVO(15, 24,"Ментос", 	90),
				new ProductVO(15, 25,"Пастила", 	80),
				new ProductVO(15, 26,"Пастила в шоколаде", 	71),
				new ProductVO(15, 27,"Пирожное слоеное", 	51),
				new ProductVO(15, 28,"Пирожное бисквитное", 	63),
				new ProductVO(15, 29,"Пирожное песочное", 	52),
				new ProductVO(15, 30,"Пирожное воздушное с кремом", 	61),
				new ProductVO(15, 31,"Пирожное миндальное", 	63),
				new ProductVO(15, 32,"Пирожное заварное (трубочка)", 	49),
				new ProductVO(15, 33,"Пирожное вафельное", 	55),
				new ProductVO(15, 34,"Твикс", 	63),
				new ProductVO(15, 35,"Торт бисквитный с фруктовой начинкой", 	61),
				new ProductVO(15, 36,"Торт слоеный", 	42),
				new ProductVO(15, 37,"Торт миндальный", 	45),
				new ProductVO(15, 38,"Фрутелла", 	84),
				new ProductVO(15, 39,"Халва подсолнечная", 	55),
				new ProductVO(15, 40,"Халва тахинная", 	50),
				new ProductVO(15, 41,"Шоколад горький", 	48),
				new ProductVO(15, 42,"Шоколад молочный", 	52),
				
				//	Варенье
				new ProductVO(16, 1,"Абрикосовое", 	72),
				new ProductVO(16, 2,"Айвовое", 	71),
				new ProductVO(16, 3,"Грушевое", 	71),
				new ProductVO(16, 4,"Клубничное", 	74),
				new ProductVO(16, 5,"Малиновое", 	70),
				new ProductVO(16, 6,"Мандариновое", 	76),
				new ProductVO(16, 7,"Персиковое", 	67),
				new ProductVO(16, 8,"Сливовое", 	75),
				new ProductVO(16, 9,"Черносмородиновое", 	73),
				new ProductVO(16, 10,"Из черноплодки", 	75),
				new ProductVO(16, 11,"Яблочное", 	68),
				new ProductVO(16, 12,"Яблочное повидло", 	65),
				new ProductVO(16, 13,"Яблочное пюре (консерв.)", 	19),
				
				//	Мороженое
				new ProductVO(17, 1,"Молочное", 	21.3),
				new ProductVO(17, 2,"Молочное крем-брюле", 	22.9),
				new ProductVO(17, 3,"Молочное шоколадное", 	21.2),
				new ProductVO(17, 4,"Молочное с плодами ягодами", 	21.2),
				new ProductVO(17, 5,"Молочное в шоколадной глазури", 	20.6),
				new ProductVO(17, 6,"Сливочное", 	19.4),
				new ProductVO(17, 7,"Сливочное крем-брюле", 	21.4),
				new ProductVO(17, 8,"Сливочное шоколадное", 	20),
				new ProductVO(17, 9,"Сливочное с плодами и ягодами", 	20.1),
				new ProductVO(17, 10,"Сливочное в шоколадной глазури", 	19.4),
				new ProductVO(17, 11,"Пломбир", 	20.4),
				new ProductVO(17, 12,"Пломбир крем-брюле", 	22.4),
				new ProductVO(17, 13,"Пломбир шоколадный", 	20.1),
				new ProductVO(17, 14,"Пломбир с плодами и ягодами", 	21.1),
				new ProductVO(17, 15,"Пломбир в шоколадной глазури", 	20.1),
				
				//	Напитки, соки
				new ProductVO(18, 1,"Вода", 	0),
				new ProductVO(18, 2,"Минеральная вода", 	0),
				new ProductVO(18, 3,"Чай, кофе без сахара", 	0),
				new ProductVO(18, 4,"Чайный гриб", 	7),
				new ProductVO(18, 5,"Квас хлебный", 	5),
				new ProductVO(18, 6,"Кола диетическая", 	0),
				new ProductVO(18, 7,"Кока-кола", 	10.6),
				new ProductVO(18, 8,"Лимонад", 	7.5),
				new ProductVO(18, 9,"Миринда", 	12.2),
				new ProductVO(18, 10,"Пепси-кола", 	11.8),
				new ProductVO(18, 11,"Спрайт", 	10.2),
				new ProductVO(18, 12,"Фанта", 	12.9),
				new ProductVO(18, 13,"Швепс", 	12.6),
				new ProductVO(18, 14,"Абрикосовый сок", 	13),
				new ProductVO(18, 15,"Айвовый сок", 	11),
				new ProductVO(18, 16,"Ананасовый сок", 	12),
				new ProductVO(18, 17,"Апельсиновый сок", 	13),
				new ProductVO(18, 18,"Виноградный сок", 	16),
				new ProductVO(18, 19,"Вишневый сок", 	11),
				new ProductVO(18, 20,"Гранатовый сок", 	14),
				new ProductVO(18, 21,"Грейпфрутовый сок", 	8),
				new ProductVO(18, 22,"Лимонный сок", 	4),
				new ProductVO(18, 23,"Мандариновый сок", 	10),
				new ProductVO(18, 24,"Морковный сок", 	13),
				new ProductVO(18, 25,"Персиковый сок", 	17),
				new ProductVO(18, 26,"Свекольный сок", 	14),
				new ProductVO(18, 27,"Сливовый сок", 	15),
				new ProductVO(18, 28,"Томатный сок", 	3),
				new ProductVO(18, 29,"Черносмородиновый сок", 	7.5),
				new ProductVO(18, 30,"Черноплоднорябиновый сок", 	11),
				new ProductVO(18, 31,"Шиповниковый сок", 	16),
				new ProductVO(18, 32,"Яблочный сок	", 	10),
				
				//	Алкоголь
				new ProductVO(19, 1	,"Абсент",  1.5 ),
			    new ProductVO(19, 2	,"Бренди",  0 ),
			    new ProductVO(19, 3	,"Водка",  0 ),
			    new ProductVO(19, 4	,"Виски",  0 ),
			    new ProductVO(19, 5	,"Джин",  0 ),
			    new ProductVO(19, 6 ,"Джин с тоником",  7 ),
			    new ProductVO(19, 7 ,"Коньяк",  0 ),
			    new ProductVO(19, 8 ,"Ром",  0 ),
			    new ProductVO(19, 9 ,"Текила",  0 ),
			    new ProductVO(19, 10 ,"Шампанское сухое",  0.5 ),
			    new ProductVO(19, 11 ,"Шампанское полусухое",  2.5 ),
			    new ProductVO(19, 12 ,"Шампанское полусладкое",  5 ),
			    new ProductVO(19, 13 ,"Шампанское сладкое",  8 ),
			    new ProductVO(19, 14 ,"Вино сухое красное",  1 ),
			    new ProductVO(19, 15 ,"Вино сухое белое",  1 ),
			    new ProductVO(19, 16 ,"Вино полусухое красное",  2.5 ),
			    new ProductVO(19, 17 ,"Вино полусухое белое",  2.5 ),
			    new ProductVO(19, 18 ,"Вино полусладкое красное",  5 ),
			    new ProductVO(19, 19 ,"Вино полусладкое белое",  5 ),
			    new ProductVO(19, 20 ,"Вино сладкое красное",  8 ),
			    new ProductVO(19, 21 ,"Вино сладкое белое",  8 ),
			    new ProductVO(19, 22 ,"Крепкие вина",  12 ),
			    new ProductVO(19, 23 ,"Вино «Лидия»",  10 ),
			    new ProductVO(19, 24 ,"Вино «Николь»",  12 ),
			    new ProductVO(19, 25 ,"Вино «Кагор»",  16 ),
			    new ProductVO(19, 26 ,"Десертные вина",  20 ),
			    new ProductVO(19, 27 ,"Бюссо",  14 ),
			    new ProductVO(19, 28 ,"Букет Молдавии",  16 ),
			    new ProductVO(19, 29 ,"Вермут бьянко",  16.5 ),
			    new ProductVO(19, 30 ,"Ганча бьянко",  17 ),
			    new ProductVO(19, 31 ,"Ганча россо",  17 ),
			    new ProductVO(19, 32 ,"Мартини россо",  14.5 ),
			    new ProductVO(19, 33 ,"Мартини розе",  16 ),
			    new ProductVO(19, 34 ,"Мартини бьянко",  16 ),
			    new ProductVO(19, 35 ,"Мартини экстра драй",  25 ),
			    new ProductVO(19, 36 ,"Перлино бьянко",  14 ),
			    new ProductVO(19, 37 ,"Рикордонно бьянко",  16.5 ),
			    new ProductVO(19, 38 ,"Сальвадоре бланко",  16 ),
			    new ProductVO(19, 39 ,"Чинзано розе",  14.5 ),
			    new ProductVO(19, 40 ,"Чинзано россо",  15 ),
			    new ProductVO(19, 41 ,"Чинзано бьянко",  18 ),
			    new ProductVO(19, 42 ,"Амаретто",  17 ),
			    new ProductVO(19, 43 ,"Бейлис",  20 ),
			    new ProductVO(19, 44 ,"Гран-Марнье",  25 ),
			    new ProductVO(19, 45 ,"Дулис",  28 ),
			    new ProductVO(19, 46 ,"Кримфилд",  23 ),
			    new ProductVO(19, 47 ,"Лаппония",  33 ),
			    new ProductVO(19, 48 ,"Куантро",  25 ),
			    new ProductVO(19, 49 ,"Малибу",  20 ),
			    new ProductVO(19, 50 ,"Мари Бризард апельсиновый",  20 ),
			    new ProductVO(19, 51 ,"Мари Бризард вишневый",  25 ),
			    new ProductVO(19, 52 ,"Мари Бризард голубой кюрасо",  35 ),
			    new ProductVO(19, 53 ,"Мари Бризард земляничный",  28 ),
			    new ProductVO(19, 54 ,"Мари Бризард кокосовый",  21 ),
			    new ProductVO(19, 55 ,"Моцарт черный шоколад",  21 ),
			    new ProductVO(19, 56 ,"Старый Таллин",  32 ),
			    new ProductVO(19, 57 ,"Шеридан",  10 ),
			    new ProductVO(19, 58 ,"Кампари биттер",  25 ),
			    new ProductVO(19, 59 ,"Кампари розовое",  25 ),
			    new ProductVO(19, 60 ,"Ксевен Амброс",  20 ),
			    new ProductVO(19, 61 ,"Ксевен Руби",  20 ),
			    new ProductVO(19, 62 ,"Ксевен Коко",  25 ),
			    new ProductVO(19, 63 ,"Мартини биттер",  30 ),
			    new ProductVO(19, 64 ,"Рикардонно бьянко",  16.5 ),
			    new ProductVO(19, 65 ,"Настойка «Клюква на коньяке»",  19 ),
			    new ProductVO(19, 66 ,"Пиво Арсенальное классика",  4.2 ),
			    new ProductVO(19, 67 ,"Пиво Арсенальное крепкое",  4.4 ),
			    new ProductVO(19, 68 ,"Пиво Балтика №0",  6.1 ),
			    new ProductVO(19, 69 ,"Пиво Балтика №3-4",  4.8 ),
			    new ProductVO(19, 70 ,"Пиво Балтика №5",  3 ),
			    new ProductVO(19, 71 ,"Пиво Балтика №6",  6 ),
			    new ProductVO(19, 72 ,"Пиво Балтика №7",  4.5 ),
			    new ProductVO(19, 73 ,"Пиво Балтика №8",  3.4 ),
			    new ProductVO(19, 74 ,"Пиво Балтика №9",  3.7 ),
			    new ProductVO(19, 75 ,"Пиво Бочкарев светлое",  3.6 ),
			    new ProductVO(19, 76 ,"Пиво Будвайзер",  3 ),
			    new ProductVO(19, 77 ,"Пиво Волжанин светлое",  4.6 ),
			    new ProductVO(19, 78 ,"Пиво Велкопоповицкий козел",  3.4 ),
			    new ProductVO(19, 79 ,"Пиво Доктор Дизель",  6.2 ),
			    new ProductVO(19, 80 ,"Пиво Дон классика",  4.5 ),
			    new ProductVO(19, 81 ,"Пиво Жигулевское",  4.6 ),
			    new ProductVO(19, 82 ,"Пиво Золотая бочка светлое",  4 ),
			    new ProductVO(19, 83 ,"Пиво Клинское светлое",  4.6 ),
			    new ProductVO(19, 84 ,"Пиво Клинское люкс",  4.7 ),
			    new ProductVO(19, 85 ,"Пиво Красный Восток",  3.2 ),
			    new ProductVO(19, 86 ,"Пиво Крушовице светлое",  4.4 ),
			    new ProductVO(19, 87 ,"Пиво Крушовице темное",  3.9 ),
			    new ProductVO(19, 88 ,"Пиво Ловенброу светлое",  3.4 ),
			    new ProductVO(19, 89 ,"Пиво Миллер",  3.5 ),
			    new ProductVO(19, 90 ,"Пиво Невское светлое",  4.6 ),
			    new ProductVO(19, 91 ,"Пиво Невское лайт",  3.5 ),
			    new ProductVO(19, 92 ,"Пиво Оболонь лагер",  4 ),
			    new ProductVO(19, 93 ,"Пиво Охота крепкое",  4.5 ),
			    new ProductVO(19, 94 ,"Пиво Пит светлое",  4.6 ),
			    new ProductVO(19, 95 ,"Пиво Сибирская корона классическое",  4.7 ),
			    new ProductVO(19, 96 ,"Пиво Сибирская корона праздничное",  5.8 ),
			    new ProductVO(19, 97 ,"Пиво Сокол светлое",  4.2 ),
			    new ProductVO(19, 98 ,"Пиво Солодов классика",  3.2 ),
			    new ProductVO(19, 99 ,"Пиво Старый мельник классика",  5.3 ),
			    new ProductVO(19, 100 ,"Пиво Старый мельник светлое",  4.6 ),
			    new ProductVO(19, 101 ,"Пиво Тинькофф лайт",  4.2 ),
			    new ProductVO(19, 102 ,"Пиво Тинькофф платиновое",  5.3 ),
			    new ProductVO(19, 103 ,"Пиво Тинькофф золотое",  5.8 ),
			    new ProductVO(19, 104 ,"Пиво Три медведя",  4.6 ),
			    new ProductVO(19, 105 ,"Пиво Хайнекен",  3 ),
			    new ProductVO(19, 106 ,"Пиво Холстен премиум",  3.2 ),
			    new ProductVO(19, 107 ,"Пиво Эфес светлое",  4.7 ),
			    new ProductVO(19, 108 ,"Пиво Ярпиво оригинальное",  4.6 ),
			    new ProductVO(19, 109 ,"Пиво Ярпиво элитное",  5.3 ),
			    new ProductVO(19, 110 ,"Пиво Ярпиво крепкое",  5.8 ),
			    new ProductVO(19, 111 ,"Пиво Ярпиво янтарное",  4.7 )

			]		
		);
		
		public function getProductsByCategory(category:CategoryVO):ArrayCollection
		{
		 	var result:ArrayCollection = new ArrayCollection();
			if(category)
			{
				for each(var item:ProductVO in products)
				{
					if(item.categoryId == category.id)
					{
						result.addItem(item);
					}
				}
			}
			return result;
		}
		
		public function getProductsByCategoryId(categoryId:int):ArrayCollection
		{
			var result:ArrayCollection = new ArrayCollection();
			
				for each(var item:ProductVO in products)
				{
					if(item.categoryId == categoryId)
					{
						result.addItem(item);
					}
				}
			
			return result;
		}		
		
	}
}